"""Tests for the chunked DNA importer.

Uses fakeredis + mongomock to avoid requiring live services in CI.
Falls back to live Redis/Mongo if the mocks are not installed.
"""

import time
import pytest

# ---------------------------------------------------------------------------
# Attempt to import mock backends; skip gracefully if unavailable
# ---------------------------------------------------------------------------
try:
    import fakeredis
    HAS_FAKEREDIS = True
except ImportError:
    HAS_FAKEREDIS = False

try:
    import mongomock
    HAS_MONGOMOCK = True
except ImportError:
    HAS_MONGOMOCK = False

from healthagent.chunk_importer import DNAChunkImporter, probe_system, SystemResources

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

SAMPLE_23ANDME = """\
# This data file generated by 23andMe
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tAA
rs3094315\t1\t752566\tAG
rs12124819\t1\t776546\tAA
rs28765502\t2\t592938\tCC
rs7417106\t2\t785011\tGG
rs2980319\tX\t572463\tAT
rs2905036\tX\t723891\tCC
rs4422948\tMT\t16519\tCC
"""


# ---------------------------------------------------------------------------
# System probe tests  (no external services needed)
# ---------------------------------------------------------------------------

class TestSystemProbe:

    def test_returns_system_resources(self):
        res = probe_system()
        assert isinstance(res, SystemResources)

    def test_cpu_cores_positive(self):
        res = probe_system()
        assert res.cpu_cores >= 1

    def test_ram_available_positive(self):
        res = probe_system()
        assert res.ram_available_mb > 0

    def test_recommended_threads_within_bounds(self):
        res = probe_system(min_threads=2, max_threads=8)
        assert 2 <= res.recommended_threads <= 8

    def test_recommended_chunk_lines_within_bounds(self):
        res = probe_system(min_chunk_lines=1_000, max_chunk_lines=50_000)
        assert 1_000 <= res.recommended_chunk_lines <= 50_000

    def test_report_is_string(self):
        res = probe_system()
        assert isinstance(res.report(), str)
        assert "CPU" in res.report()

    def test_cpu_free_between_0_and_100(self):
        res = probe_system()
        assert 0.0 <= res.cpu_percent_free <= 100.0


# ---------------------------------------------------------------------------
# Chunk splitting tests  (no external services needed)
# ---------------------------------------------------------------------------

class TestChunkSplitting:

    def test_split_even(self):
        lines = [f"line{i}" for i in range(100)]
        chunks = DNAChunkImporter._split_chunks(lines, 25)
        assert len(chunks) == 4
        assert all(len(c) == 25 for c in chunks)

    def test_split_remainder(self):
        lines = [f"line{i}" for i in range(103)]
        chunks = DNAChunkImporter._split_chunks(lines, 25)
        assert len(chunks) == 5          # 4 full + 1 remainder
        assert len(chunks[-1]) == 3

    def test_split_smaller_than_chunk(self):
        lines = ["a", "b", "c"]
        chunks = DNAChunkImporter._split_chunks(lines, 1000)
        assert len(chunks) == 1
        assert chunks[0] == ["a", "b", "c"]

    def test_split_empty(self):
        assert DNAChunkImporter._split_chunks([], 100) == []


# ---------------------------------------------------------------------------
# Integration tests  (require live or mocked Redis + MongoDB)
# ---------------------------------------------------------------------------

def _make_importer_with_resources() -> tuple[DNAChunkImporter, SystemResources]:
    """Return an importer configured against live local services."""
    importer = DNAChunkImporter(
        mongo_uri="mongodb://localhost:27017/",
        redis_host="localhost",
        redis_port=6379,
        db_name="healthagent_test",
    )
    res = SystemResources(
        cpu_cores=4,
        cpu_percent_free=80.0,
        ram_total_mb=8192,
        ram_available_mb=4096,
        recommended_threads=2,
        recommended_chunk_lines=3,   # tiny chunks to exercise splitting in tests
    )
    return importer, res


def _services_available() -> bool:
    """Return True if both Redis and MongoDB are reachable."""
    try:
        import redis as _redis
        _redis.Redis(host="localhost", port=6379).ping()
    except Exception:
        return False
    try:
        from pymongo import MongoClient
        MongoClient("mongodb://localhost:27017/", serverSelectionTimeoutMS=1000).admin.command("ping")
    except Exception:
        return False
    return True


requires_services = pytest.mark.skipif(
    not _services_available(),
    reason="Redis or MongoDB not available",
)


@requires_services
class TestChunkImporterIntegration:

    def setup_method(self):
        """Drop test database before each test."""
        from pymongo import MongoClient
        client = MongoClient("mongodb://localhost:27017/")
        client.drop_database("healthagent_test")
        client.close()

    def test_import_string_returns_summary(self):
        importer, res = _make_importer_with_resources()
        summary = importer.import_string(SAMPLE_23ANDME, resources=res, job_id="test-001")
        assert summary["job_id"] == "test-001"
        assert summary["snp_count"] == 8
        assert summary["status"] == "done"

    def test_creates_per_chromosome_collections(self):
        importer, res = _make_importer_with_resources()
        importer.import_string(SAMPLE_23ANDME, resources=res, job_id="test-002")
        cols = importer.list_collections()
        assert "chr_1" in cols
        assert "chr_2" in cols
        assert "chr_X" in cols
        assert "chr_MT" in cols

    def test_multiple_chunks_produced(self):
        importer, res = _make_importer_with_resources()
        # chunk_size=3, 8 data lines → ceil(8/3) = 3 chunks
        summary = importer.import_string(SAMPLE_23ANDME, resources=res, job_id="test-003")
        assert summary["chunk_count"] >= 2

    def test_redis_job_status_done(self):
        importer, res = _make_importer_with_resources()
        importer.import_string(SAMPLE_23ANDME, resources=res, job_id="test-004")
        status = importer.job_status("test-004")
        assert status["status"] == "done"
        assert status["snp_count"] == 8
        assert status["progress_pct"] == 100.0

    def test_mongo_snp_documents_have_required_fields(self):
        from pymongo import MongoClient
        importer, res = _make_importer_with_resources()
        importer.import_string(SAMPLE_23ANDME, resources=res, job_id="test-005")
        client = MongoClient("mongodb://localhost:27017/")
        doc = client["healthagent_test"]["chr_1"].find_one()
        assert doc is not None
        for field in ("rsid", "chromosome", "position", "genotype", "job_id", "chunk_index"):
            assert field in doc, f"Missing field: {field}"
        client.close()

    def test_snp_count_matches_across_collections(self):
        from pymongo import MongoClient
        importer, res = _make_importer_with_resources()
        importer.import_string(SAMPLE_23ANDME, resources=res, job_id="test-006")
        client = MongoClient("mongodb://localhost:27017/")
        db = client["healthagent_test"]
        total = sum(db[c].count_documents({}) for c in db.list_collection_names())
        assert total == 8
        client.close()

    def test_probe_system_live(self):
        """Smoke test: probe_system() reflects real machine state."""
        res = probe_system()
        assert res.ram_available_mb > 0
        assert res.recommended_threads >= 2
