"""Tests for the DNA file importer."""

import pytest
from healthagent.dna_importer import (
    DNAFormat,
    import_dna_string,
)

TWENTYTHREE_SAMPLE = """\
# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2024
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tAA
rs3094315\t1\t752566\tAG
rs12124819\t1\t776546\tAA
"""

ANCESTRY_SAMPLE = """\
# AncestryDNA raw data download
rsid\tchromosome\tposition\tallele1\tallele2
rs4477212\t1\t82154\tA\tA
rs3094315\t1\t752566\tA\tG
rs12124819\t1\t776546\tA\tA
"""

MYHERITAGE_SAMPLE = """\
# MyHeritage DNA raw data
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tAA
rs3094315\t1\t752566\tAG
"""

FAMILYTREEDNA_SAMPLE = """\
RSID,CHROMOSOME,POSITION,RESULT
rs4477212,1,82154,AA
rs3094315,1,752566,AG
rs12124819,1,776546,AA
"""

VCF_SAMPLE = """\
##fileformat=VCFv4.1
##source=23andMe
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO
1\t82154\trs4477212\tA\tA\t.\t.\t.
1\t752566\trs3094315\tA\tG\t.\t.\t.
"""


def test_23andme_detection():
    profile = import_dna_string(TWENTYTHREE_SAMPLE)
    assert profile.source_format == DNAFormat.TWENTYTHREE_AND_ME


def test_ancestry_detection():
    profile = import_dna_string(ANCESTRY_SAMPLE)
    assert profile.source_format == DNAFormat.ANCESTRY_DNA


def test_myheritage_detection():
    profile = import_dna_string(MYHERITAGE_SAMPLE)
    assert profile.source_format == DNAFormat.MY_HERITAGE


def test_familytreedna_detection():
    profile = import_dna_string(FAMILYTREEDNA_SAMPLE)
    assert profile.source_format == DNAFormat.FAMILY_TREE_DNA


def test_vcf_detection():
    profile = import_dna_string(VCF_SAMPLE)
    assert profile.source_format == DNAFormat.VCF


def test_23andme_snp_count():
    profile = import_dna_string(TWENTYTHREE_SAMPLE)
    assert profile.snp_count == 3


def test_ancestry_genotype_merged():
    profile = import_dna_string(ANCESTRY_SAMPLE)
    snp = profile.get_snp("rs3094315")
    assert snp is not None
    assert snp.genotype == "AG"


def test_snp_lookup():
    profile = import_dna_string(TWENTYTHREE_SAMPLE)
    snp = profile.get_snp("rs4477212")
    assert snp.chromosome == "1"
    assert snp.position == 82154
    assert snp.genotype == "AA"


def test_empty_file_raises():
    with pytest.raises(ValueError):
        import_dna_string("")


def test_missing_file_raises():
    from healthagent.dna_importer import import_dna_file
    with pytest.raises(FileNotFoundError):
        import_dna_file("/nonexistent/path/dna.txt")
